# Thid workflow will build and push the import pipeline container.
# the plan later will be to include unit tests as well


name: Building Containers

on:
 push:
  branches:
    'master'

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build
        run: docker build -f Dockerfile -t afgreen/rna-type-models .

      - name: docker push
        run: docker push afgreen/rna-type-models

  convert-to-singularity:
    needs: create-docker-image
    name: "Pull docker image and convert"
    runs-on: ubuntu-latest

    container:
      image: quay.io/singularity/singularity:v3.8.1
      options: --privileged

    steps:
      - name: "Pull image"
        run: |
          singularity pull  --name rna-type-models.sif docker://afgreen/rna-type-models:latest

      - name: "Push to ghcr"
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push rna-type-models-latest.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
